conf-version = 1

# For CI Sample

# .htpasswd format
basicauth = ["user:SAJ0dfalwUo1."] # for CI -- user:pass

server_port = "8080" # proxy server listen port
proxy_address = "http://nginx-app:8080" # proxy_pass

cookie_lifetime = 30 # min
# if the rest of this cookie life time < cookie_refresh_time -> try to republish
cookie_refresh_time = 15

# inner (in memory) or redis
# for redis example: "my-redis:6379"
auth_store = "inner"
# auth_store = "my-redis:6379"

# This option only apply when auth_store = "inner".
# It implies that the max size of inner cookie information.
max_auth_store_size = 16
