conf-version = 2

# For CI Sample

# .htpasswd format
basicauth = ["user:$2a$10$etIpH1oxl4Ky5koV2AzyYe42caqi/tvtme/UTwxA7lHlB2loLDOte"] # for CI -- user:pass

server_port = "8080" # proxy server listen port
proxy_address = "http://localhost:8888" # proxy_pass

cookie_lifetime = 43200 # min

# Prometheus exporter port
exporter_port = "9100"
